### ISSUE TITLE
unable to publish C code using microMLgen

### ISSUE THREAD

**Issue by Severus11** [eloquentarduino/EloquentMicroML#3]
Used MicroMLgen to generate c file to convert a Wifi scan result into a feature vector for classification.
Came across the following error: 

- Traceback (most recent call last):
  File "C:\Users\parth\Documents\Arduino\Wifi-Indoor positioning\feature-generator.py", line 10, in <module>
    X, y, classmap, converter_code = port_wifi_indoor_positioning(samples)
  File "C:\Python37\lib\site-packages\micromlgen\wifiindoorpositioning.py", line 60, in port_wifi_indoor_positioning
    classmap = get_classmap(samples)
  File "C:\Python37\lib\site-packages\micromlgen\wifiindoorpositioning.py", line 21, in get_classmap
    locations = list(parse_samples(samples, parser))
  File "C:\Python37\lib\site-packages\micromlgen\wifiindoorpositioning.py", line 7, in parse_samples
    for line in samples.split('\n'):
AttributeError: 'dict' object has no attribute 'split'

**Comment by SimoneS93** [comment]
Please wait a couple more days for me to find out what's wrong.
